language: node_js
node_js:
  - stable
install:
  - npm install -g codecov
notifications:
  slack:
    secure: fRVySVRH94rjqpFvI9eTDwngZNLDfrG7YhKC3riF0lPhTMA6d1wT7qmYPH0tGNzTtF6je84aMHbxydpnzYo3Dl3yB8cKMXKp16zGm9eEI6U0C9jm13yUUPTAsc6GORqlDdlS6qt09im9y+lLeAgTIXXsxh+B7yrH03wx4bJNsJKPyjhqWaD5UfFUUFYDYNvXzpzp5H/ZJNRxNjwNKAdQJAJkCD5d3436Ai6SipC6yk4tQJjPxez7X290h17bU/jvlhktKCRgUqUnj3c3bb3hX2pAHvfDfQ4H6Fh/9qS21KD9UOzYoLQLd/jbXXeJ4xB84F95npHo1MJ1+nc+UaQ/mS1pL248AA8sRuyTyk6xRV0Y373mSUR09C7CXiI8N3DH6uWiEyTzoIbam6iafe+OKknSRdu9F9H9ZXsmxSUCQWzhjEyFurYNukps/JRhl5ifK5qN+oIshlLnnzRXh7t9dtWOWa6HRO5h2y6je3xVa09xqDAZlvXugT+BNlKF8npDKxxKfWB5qMy2Tq5xK5RpvzWy2Mzs9DmfSD7CtaeZ8Y0C/Tu0lFtIeIW8V95vMHmLA2oMGWsMzqD1HX5oHJriGIZJ0DWkabyQWkYgxjrEn0QUF2ZpEBs1LvhPnHMX8nG0FwWND5jfriABSZEYBtniSlsShBTw2arK/Ue2FYET74I=
script:
  - codecov
  - bash <(curl -gits https://codecov.io/bash)
env:
  global:
    secure: pLXPu6Mqwbf7lXjHX2wgmspDlaq2ItAv6dncL49CPUVzoyYiXJpdV1AxYL0absOjtotg18nIjIqYxtt/ELLSPG6Bk3IslN4N5DNQ7Mpj9v6CVDmBR4BiRrY1q5uj6iGDhmp1s1iZtp8lqoaHo8yWjZ3JfKxNfh7D6Qpuct7u8NS+ejyngWEMpF8vzaLujlzRWSFEUo/sG/Z68RCBJv5tNqssom6Vhk1Sm+VgaTqx0uplP51cHRRVhxwYckSUB/4RUhQyfiAZupaxAwdE1368u05FiB5LU9/pUxAo37opF4UlqCtICdh4KT2YCV755lY2y8HcRLwrcr2NyJ4sZ7E2RN+wq6SjmEYDgZKCHCHB0QsF17dHc7kFyymhffUuY7zdtSqY49Drtr+QkQuRirdDfvUL8qSL5PvAKgaGMqnz20kmw2pBTNFITOVH9fai5VxEpI8smSUnDlNtQjBVGhoWuf/P2BYiIB/nOe2eBM0GtcVYpRVAIKFIZ1A7+GzcBHJmm3IuDwHQ5I3lk5sKQuv3TBRGWwD3ajmPLF/bWlsPSldha+OW8G9NNgw1pq7pzastMCBAP9xjGRu/rQeNztNi+BfF5u6VmsyI+kgiQTnZJUIza6RznDp481AQVqLD3cZJja/HSA0C5oFXGBsEkl4YC0NrG8hDty9h8aZwniF14p4=
