language: node_js
node_js:
- stable
install:
- npm install -g codecov
notifications:
  slack:
    secure: dRctgrKaVzH22FMSTR61LCLi2a3OS4lQknGFklM6WGpy7zJDWsxs55gR9q6lIaTTlNkX6EhXDlANktvyVSrsxpn8YqHjHzyDtx2Dx9x7qPaHykW6cMH/OahqpQihkJIrIm4Kmyo91QMzSxgWXKv7CVk5eXyziVKQWjOazMP/cycBM1gHQ5YIX63VEhkfv/kGOZnNSOTjqzlS7FWAlXbz14sovWx8TKfld0vbJ6EeSc6yHb9yWp3A5cU6qyrB3GcfRwn9CF8tGsM7SL0bFTRFMGoh+3N/Mg7mAmCzaX3u/BIjKsueR0EGvS098eqBAV1wLL7G17SOFQb3T47UCmn2pNH+3knwyGJvaUd2m+DRdjYI4MPw9R5p/y08m6x938vGxUeUaVYnvZMcaPbxqViBuM2630Ar8xV6E0xdUV/uyWdXheses3KfpDbdu72Dr+T6YAcHKSeqRP8hFPnvT1IQDcP/UJkP+T/I4FRKM+OF1Ya/XcHj9yXB6mGGGO7lNB2Vnn/CoLa6cf1eWRckV2gs8HbEf0OH0Ngot73SgVw/Vu3wPcWjtOsWns5W/jzPQ4fHQPUGbNSN/bgNwnjA6XYEBw/ugMccXNQ5j+5ZSXqSnMF/BTOscSuzdoDbLYOU/3Id5PJNLYuL7dzCarhBQ7xOifE4o3EDcAqgwiqM0ZdO5E8=
script:
- codecov
- bash <(curl -gits https://codecov.io/bash)
env:
  global:
    secure: pLXPu6Mqwbf7lXjHX2wgmspDlaq2ItAv6dncL49CPUVzoyYiXJpdV1AxYL0absOjtotg18nIjIqYxtt/ELLSPG6Bk3IslN4N5DNQ7Mpj9v6CVDmBR4BiRrY1q5uj6iGDhmp1s1iZtp8lqoaHo8yWjZ3JfKxNfh7D6Qpuct7u8NS+ejyngWEMpF8vzaLujlzRWSFEUo/sG/Z68RCBJv5tNqssom6Vhk1Sm+VgaTqx0uplP51cHRRVhxwYckSUB/4RUhQyfiAZupaxAwdE1368u05FiB5LU9/pUxAo37opF4UlqCtICdh4KT2YCV755lY2y8HcRLwrcr2NyJ4sZ7E2RN+wq6SjmEYDgZKCHCHB0QsF17dHc7kFyymhffUuY7zdtSqY49Drtr+QkQuRirdDfvUL8qSL5PvAKgaGMqnz20kmw2pBTNFITOVH9fai5VxEpI8smSUnDlNtQjBVGhoWuf/P2BYiIB/nOe2eBM0GtcVYpRVAIKFIZ1A7+GzcBHJmm3IuDwHQ5I3lk5sKQuv3TBRGWwD3ajmPLF/bWlsPSldha+OW8G9NNgw1pq7pzastMCBAP9xjGRu/rQeNztNi+BfF5u6VmsyI+kgiQTnZJUIza6RznDp481AQVqLD3cZJja/HSA0C5oFXGBsEkl4YC0NrG8hDty9h8aZwniF14p4=
